export const FETCH_COUNTRIES = 'COUNTRIES/FETCH_COUNTRIES';
export const FETCH_COUNTRY = 'COUNTRY/FETCH_COUNTRY';
export const LOADER_ACTIVATE = 'PAGE/LOADER_ACTIVATE';
export const LOADER_DEACTIVATE = 'PAGE/LOADER_DEACTIVATE';